// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCotdyaZIz1nHXgLqPWSIX8lt2erKeR8Xc',
    appId: '1:949939380299:web:09274ad31ff7e91c3d2dce',
    messagingSenderId: '949939380299',
    projectId: 'mollery-63499',
    authDomain: 'mollery-63499.firebaseapp.com',
    databaseURL: 'https://mollery-63499-default-rtdb.firebaseio.com',
    storageBucket: 'mollery-63499.appspot.com',
    measurementId: 'G-L5880BNR05',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTiUxtHJF9KPxDP1-fnpnyxzhJg93ELq4',
    appId: '1:949939380299:android:026c97da4b0ddf5d3d2dce',
    messagingSenderId: '949939380299',
    projectId: 'mollery-63499',
    databaseURL: 'https://mollery-63499-default-rtdb.firebaseio.com',
    storageBucket: 'mollery-63499.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmeiV4qx6GDYT1DnnvUbwQc5aYB8_R6mI',
    appId: '1:949939380299:ios:132e39761ff7b70d3d2dce',
    messagingSenderId: '949939380299',
    projectId: 'mollery-63499',
    databaseURL: 'https://mollery-63499-default-rtdb.firebaseio.com',
    storageBucket: 'mollery-63499.appspot.com',
    androidClientId: '949939380299-1h2dd287fe3bcgt2971cprvr3n1m3lpu.apps.googleusercontent.com',
    iosClientId: '949939380299-glgam5e8kdtp5aqi9jj76v39ika1mgak.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileStudioGallery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmeiV4qx6GDYT1DnnvUbwQc5aYB8_R6mI',
    appId: '1:949939380299:ios:7db2a58693dd37793d2dce',
    messagingSenderId: '949939380299',
    projectId: 'mollery-63499',
    databaseURL: 'https://mollery-63499-default-rtdb.firebaseio.com',
    storageBucket: 'mollery-63499.appspot.com',
    androidClientId: '949939380299-1h2dd287fe3bcgt2971cprvr3n1m3lpu.apps.googleusercontent.com',
    iosClientId: '949939380299-pvpokf3fi5u5mcdf8e9tf66timg338ni.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileStudioGallery.RunnerTests',
  );
}
